<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'gloss354_prst6');
define('_DB_USER_', 'gloss354_prst6');
define('_DB_PASSWD_', 'LOeXJ9VIgQ9gpN');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'zNu59VMEBM1pcH6lQarJF8QQKIgH572wvr5Sk6upg1YoVaqxKj5O3chA9g0s3vhA');
define('_COOKIE_IV_', 'bEsLkkSU');
define('_PS_CREATION_DATE_', '2013-01-11');
define('_PS_VERSION_', '1.5.4.1');
define('_RIJNDAEL_KEY_', 'Fw5Mzz6l3jpDb4enW7d05FA2eLFy9dH6');
define('_RIJNDAEL_IV_', 'XDkOyvK5B7ENpg4u');
define('_PS_DIRECTORY_', '/../../');
